<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
	        <title>HappyLand</title>
	        <link href="/inc/style.css" rel="STYLESHEET" type="text/css" media="screen" />
		<!--[if IE]>
		<link rel="stylesheet" type="text/css" href="/inc/iehacks.css" media="screen"/>
		<![endif]-->
		<link rel="shortcut icon" href="/inc/images/favicon.ico" />
		<link rel="stylesheet" href="/inc/lightbox.css" type="text/css" media="screen" />
		<script type="text/javascript" src="/inc/prototype.js"></script>
		<script type="text/javascript" src="/inc/scriptaculous.js?load=effects,builder"></script>
		<script type="text/javascript" src="/inc/lightbox.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-185490-13', 'feedtheducksproductions.com');
  ga('send', 'pageview');

  </script>
	</head>
	<body>
		<div id="container">	
			<div id="header">
				<span id="headertext">HappyLand</span>
				<ul>
					<li><a title="Gallery" id="gallery" href="/gallery.shtml">Gallery</a></li>
					<li><a title="Show History" id="history" href="/history.shtml">Show History</a></li>
					<li><a title="About" id="about" href="/about.shtml">About</a></li>
				</ul>
			</div>
			<div id="content">
